# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.29
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: false
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Glo Networks
org_slug: GlodoUK
rebel_module_groups: []
repo_description: This project aims to deal with modules related to the account modules
    of Odoo.
repo_name: Accounts addons for Odoo
repo_slug: account
repo_website: https://github.com/GlodoUK/account
use_pyproject_toml: false
use_ruff: false

